SPRING_PORT=8888
SPRING_PROFILES_ACTIVE=pro

SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/campuslearning
SPRING_DATASOURCE_USERNAME=root
SPRING_DATASOURCE_PASSWORD=dungcon2005
SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

SPRING_RABBITMQ_HOST=rabbitmq
SPRING_RABBITMQ_PORT=5672
SPRING_RABBITMQ_USERNAME=guest
SPRING_RABBITMQ_PASSWORD=guest

SPRING_REDIS_HOST=redis
SPRING_REDIS_PORT=6379

SPRING_REDIS_COMMENT_HOST=redis-comment
SPRING_REDIS_COMMENT_PORT=6379

SPRING_REDIS_CONVERSATION_HOST=redis-conversation
SPRING_REDIS_CONVERSATION_PORT=6379

SPRING_REDIS_MESSAGE_HOST=redis-message
SPRING_REDIS_MESSAGE_PORT=6379

SPRING_REDIS_STORY_HOST=redis-story
SPRING_REDIS_STORY_PORT=6379

GEMINI_API_KEY=AIzaSyDj4ELScbmlrxwB3FRPS08z-U7zbrHx3z4
GOOGLE_CLIENT_ID=687543650693-istlhoe28vq9adl28v5lc9ojkhgo47mj.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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

PAYPAL_CLIENT_ID=AWwRq7yNKOWYuCtZNC3Ij...
PAYPAL_CLIENT_SECRET=EDIK36KtkVIPmVIL8y3d6qj6naXgTwrZn6ue6AWf8iHVrAbLwJBwaWaJZzk7hPYQTUDxuSTBVskVyJZm
PAYPAL_MODE=sandbox

JWT_SECRET=Igf4IQ6BKCNvbT9fehqgHP1gpJZ2Bx1Qm4F6ZAUXEgQTcJTBKukpvYfpKL/0GQZv
JWT_EXPIRATION=3600000
