version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dungcon2005
      MYSQL_DATABASE: campuslearning
    ports:
      - "5001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5002:5672"
      - "5003:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    ports:
      - "5004:6379"
    networks:
      - app-net

  redis-comment:
    image: redis:7-alpine
    container_name: redis_comment_container
    restart: always
    ports:
      - "5005:6379"
    networks:
      - app-net

  redis-conversation:
    image: redis:7-alpine
    container_name: redis_conversation_container
    restart: always
    ports:
      - "5006:6379"
    networks:
      - app-net

  redis-message:
    image: redis:7-alpine
    container_name: redis_message_container
    restart: always
    ports:
      - "5007:6379"
    networks:
      - app-net

  redis-story:
    image: redis:7-alpine
    container_name: redis_story_container
    restart: always
    ports:
      - "5008:6379"
    networks:
      - app-net

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: damdung/campuslearning-spring-app:latest
    container_name: spring_container_2
    restart: always
    env_file:
      - /home/nguyenducduong/campuslearning/configs/.env.user.dev
      - /home/nguyenducduong/campuslearning/configs/.env.user.pro
    depends_on:
      eureka-server:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      redis-comment:
        condition: service_started
      redis-conversation:
        condition: service_started
      redis-message:
        condition: service_started
      redis-story:
        condition: service_started
    ports:
      - "${SPRING_PORT}:8080"
    networks:
      - app-net
    volumes:
      - /home/nguyenducduong/campuslearning/uploads:/app/uploads

  spring-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    image: damdung/campuslearning-spring-app:latest
    container_name: spring_container_3
    restart: always
    env_file:
      - /home/nguyenducduong/campuslearning/configs/.env.user.dev
      - /home/nguyenducduong/campuslearning/configs/.env.user.pro
    depends_on:
      eureka-server:
        condition: service_started
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
      redis-comment:
        condition: service_started
      redis-conversation:
        condition: service_started
      redis-message:
        condition: service_started
      redis-story:
        condition: service_started
    ports:
      - "8887:8080"
    networks:
      - app-net
    volumes:
      - /home/nguyenducduong/campuslearning/uploads:/app/uploads

  code-server:
    image: codercom/code-server:4.105.0
    container_name: code_server_container
    restart: always
    command: --auth none --bind-addr 0.0.0.0:8080
    ports:
      - "5009:8080"
    volumes:
      - ./workspace:/home/coder/project
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./k8s:/etc/prometheus
    ports:
      - "5010:9090"
    networks:
      - app-net
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "5011:3000"
    depends_on:
      - prometheus
    networks:
      - app-net
    restart: always

  eureka-server:
    build: ./Eureka-Server
    container_name: eureka-server
    ports:
      - "5012:8761"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8686:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-net

networks:
  app-net:

volumes:
  mysql_data:
  jenkins_home:
